Fix strict C icx error in base alloc test
This commit fixes following:
error: a function declaration without a prototype is
deprecated in all versions of C [-Werror,-Wstrict-prototypes]

Signed-off-by: Krzysztof Filipek <krzysztof.filipek@intel.com>